version: '3'
services:
   notebook:
#      build: . 
      image: aot29/topic_modeling
      container_name: topic_modeling_notebook
      ports:
        - "9999:8888"
      volumes:
        - "./:/home/jovyan"
      tty: true

